const ClientForm = [
    {
      businessId: "@boldbrewcoffee",
      businessName: "Bold Brew Coffee",
      businessEmail: "coffee@gmail.com",
      businessType: "Coffee Shop",
      lastLog: "5 hours ago",
      joinedDate: "May, 2023",
      viewProfile: "View Profile",
    },
    {
      businessId: "@brewbold",
      businessName: "Brew Bold Coffee",
      businessEmail: "brewbold@gmail.com",
      businessType: "Coffee Shop",
      lastLog: "2 hours ago",
      joinedDate: "June, 2023",
      viewProfile: "View Profile",
    },
    {
        businessId: "@boldbrewcoffee",
        businessName: "Bold Brew Coffee",
        businessEmail: "coffee@gmail.com",
        businessType: "Coffee Shop",
        lastLog: "5 hours ago",
        joinedDate: "May, 2023",
        viewProfile: "View Profile",
      },
      {
        businessId: "@brewbold",
        businessName: "Brew Bold Coffee",
        businessEmail: "brewbold@gmail.com",
        businessType: "Coffee Shop",
        lastLog: "2 hours ago",
        joinedDate: "June, 2023",
        viewProfile: "View Profile",
      },
      {
        businessId: "@boldbrewcoffee",
        businessName: "Bold Brew Coffee",
        businessEmail: "coffee@gmail.com",
        businessType: "Coffee Shop",
        lastLog: "5 hours ago",
        joinedDate: "May, 2023",
        viewProfile: "View Profile",
      },
      {
        businessId: "@brewbold",
        businessName: "Brew Bold Coffee",
        businessEmail: "brewbold@gmail.com",
        businessType: "Coffee Shop",
        lastLog: "2 hours ago",
        joinedDate: "June, 2023",
        viewProfile: "View Profile",
      },
      {
        businessId: "@boldbrewcoffee",
        businessName: "Bold Brew Coffee",
        businessEmail: "coffee@gmail.com",
        businessType: "Coffee Shop",
        lastLog: "5 hours ago",
        joinedDate: "May, 2023",
        viewProfile: "View Profile",
      },
      {
        businessId: "@brewbold",
        businessName: "Brew Bold Coffee",
        businessEmail: "brewbold@gmail.com",
        businessType: "Coffee Shop",
        lastLog: "2 hours ago",
        joinedDate: "June, 2023",
        viewProfile: "View Profile",
      },
      {
        businessId: "@brewbold",
        businessName: "Brew Bold Coffee",
        businessEmail: "brewbold@gmail.com",
        businessType: "Coffee Shop",
        lastLog: "2 hours ago",
        joinedDate: "June, 2023",
        viewProfile: "View Profile",
      },
      {
        businessId: "@boldbrewcoffee",
        businessName: "Bold Brew Coffee",
        businessEmail: "coffee@gmail.com",
        businessType: "Coffee Shop",
        lastLog: "5 hours ago",
        joinedDate: "May, 2023",
        viewProfile: "View Profile",
      },
      {
        businessId: "@brewbold",
        businessName: "Brew Bold Coffee",
        businessEmail: "brewbold@gmail.com",
        businessType: "Coffee Shop",
        lastLog: "2 hours ago",
        joinedDate: "June, 2023",
        viewProfile: "View Profile",
      },
  ];
  
  export default ClientForm;
  