import Quotation from "../../Quotation";

const QuoteArray = [
    {
      FileImg: "",
      Name: "Zoya Khan",
      QuotationNo: "ABC",
      IssueDate: "2024-06-10",
      DueDate: "2024-06-15",
      Amount: "1222k",
      Status: "Success",
      Action: "Zoya",
    },
    {
        FileImg: "",
        Name: "Zoya Khan",
        QuotationNo: "ABC",
        IssueDate: "2024-06-10",
        DueDate: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        QuotationNo: "ABC",
        IssueDate: "2024-06-10",
        DueDate: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        QuotationNo: "ABC",
        IssueDate: "2024-06-10",
        DueDate: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        QuotationNo: "ABC",
        IssueDate: "2024-06-10",
        DueDate: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        QuotationNo: "ABC",
        IssueDate: "2024-06-10",
        DueDate: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },

      {
        FileImg: "",
        Name: "Zoya Khan",
        QuotationNo: "ABC",
        IssueDate: "2024-06-10",
        DueDate: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        QuotationNo: "ABC",
        IssueDate: "2024-06-10",
        DueDate: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        QuotationNo: "ABC",
        IssueDate: "2024-06-10",
        DueDate: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        QuotationNo: "ABC",
        IssueDate: "2024-06-10",
        DueDate: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
   
      
      
];

export default QuoteArray;
