const ClientArray = [
  {
    businessImg: "path_to_image",
    UserId: "12345",
    Name: "John Doe",
    Email: "johndoe@example.com",
    Designation: "Manager",
    lastLog: "2025-01-18",
    joinedDate: "2024-06-15",
    viewProfile: "View Profile",
  },
  {
    businessImg: "path_to_image",
    UserId: "12345",
    Name: "John Doe",
    Email: "johndoe@example.com",
    Designation: "Manager",
    lastLog: "2025-01-18",
    joinedDate: "2024-06-15",
    viewProfile: "View Profile",
  },
  {
    businessImg: "path_to_image",
    UserId: "12345",
    Name: "John Doe",
    Email: "johndoe@example.com",
    Designation: "Manager",
    lastLog: "2025-01-18",
    joinedDate: "2024-06-15",
    viewProfile: "View Profile",
  },
  {
    businessImg: "path_to_image",
    UserId: "12345",
    Name: "John Doe",
    Email: "johndoe@example.com",
    Designation: "Manager",
    lastLog: "2025-01-18",
    joinedDate: "2024-06-15",
    viewProfile: "View Profile",
  },
  {
    businessImg: "path_to_image",
    UserId: "12345",
    Name: "John Doe",
    Email: "johndoe@example.com",
    Designation: "Manager",
    lastLog: "2025-01-18",
    joinedDate: "2024-06-15",
    viewProfile: "View Profile",
  },
  {
    businessImg: "path_to_image",
    UserId: "12345",
    Name: "John Doe",
    Email: "johndoe@example.com",
    Designation: "Manager",
    lastLog: "2025-01-18",
    joinedDate: "2024-06-15",
    viewProfile: "View Profile",
  },
  {
    businessImg: "path_to_image",
    UserId: "12345",
    Name: "John Doe",
    Email: "johndoe@example.com",
    Designation: "Manager",
    lastLog: "2025-01-18",
    joinedDate: "2024-06-15",
    viewProfile: "View Profile",
  },
  {
    businessImg: "path_to_image",
    UserId: "12345",
    Name: "John Doe",
    Email: "johndoe@example.com",
    Designation: "Manager",
    lastLog: "2025-01-18",
    joinedDate: "2024-06-15",
    viewProfile: "View Profile",
  },
  {
    businessImg: "path_to_image",
    UserId: "12345",
    Name: "John Doe",
    Email: "johndoe@example.com",
    Designation: "Manager",
    lastLog: "2025-01-18",
    joinedDate: "2024-06-15",
    viewProfile: "View Profile",
  },
  {
    businessImg: "path_to_image",
    UserId: "12345",
    Name: "John Doe",
    Email: "johndoe@example.com",
    Designation: "Manager",
    lastLog: "2025-01-18",
    joinedDate: "2024-06-15",
    viewProfile: "View Profile",
  },
  // More clients...
];
 export default ClientArray;