

const InvoiceArray = [
    {
      FileImg: "",
      Name: "Zoya Khan",
      InvoiceId: "ABC",
      Date: "2024-06-10",
      Type: "2024-06-15",
      Amount: "1222k",
      Status: "Success",
      Action: "Zoya",
    },
    {
        FileImg: "",
        Name: "Zoya Khan",
        InvoiceId: "ABC",
        Date: "2024-06-10",
        Type: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        InvoiceId: "ABC",
        Date: "2024-06-10",
        Type: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        InvoiceId: "ABC",
        Date: "2024-06-10",
        Type: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        InvoiceId: "ABC",
        Date: "2024-06-10",
        Type: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        InvoiceId: "ABC",
        Date: "2024-06-10",
        Type: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        InvoiceId: "ABC",
        Date: "2024-06-10",
        Type: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        InvoiceId: "ABC",
        Date: "2024-06-10",
        Type: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        InvoiceId: "ABC",
        Date: "2024-06-10",
        Type: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        InvoiceId: "ABC",
        Date: "2024-06-10",
        Type: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },
      {
        FileImg: "",
        Name: "Zoya Khan",
        InvoiceId: "ABC",
        Date: "2024-06-10",
        Type: "2024-06-15",
        Amount: "1222k",
        Status: "Success",
        Action: "Zoya",
      },

   
      
      
];

export default InvoiceArray;
